### ISSUE TITLE
Is it possible to delete useless range-diff?

### ISSUE THREAD

**Issue by adlternative** [gitgitgadget/gitgitgadget#1024]
Hi, sometime we may have a big change from vN to vN+1, the range-diff output
is useless, so is here anyway to suppress its output by some option?
@dscho

**Comment by dscho** [comment]
There is not yet any option, but it is easy to see how this could be valuable.

One strategy (easy to implement) would be a footer in the first comment similar to `Cc:`.

Another strategy (harder to implement) would be to compare the size of the range-diff to the size of the overall patches, and at a certain threshold replace the range-diff with a message like "The range-diff is too huge to be helpful."

All it needs is someone with enough time to implement either strategy (or a strategy I have not thought of, yet).

**Comment by webstech** [comment]
Looking at the second strategy.  Using [this diff](https://lore.kernel.org/git/pull.1250.v2.git.1654778272871.gitgitgadget@gmail.com/) as an example.

`/^\s+[+-][\s\n]/` is the count of changes.
`^\s+[+-]\+[\s\n]/ is the count of range changes.
In this example, there are 42 changes and 60 range changes.  The range changes are 27 ++ and 33 -+.

Possible rules (**VERY** open to suggestions and numbers):
- if the ++ count is  _x%_ greater than the -+ count, a lot of changes were added so the range-diff could still be useful
- if the -+ count is  _x%_ greater than the ++ count, a lot of changes were removed so the range-diff may not be needed
- if the ++ and -+ counts are similar and are _x%_ of the total changes (approximately 40% in the example), then the range-diff may not be needed

Given the possibilities of getting it wrong, the footer comment would still need to be supported but as a boolean: `version-diff: (yes|no)`.

How about this message?
No range-diff provided.  Please review the new patches as a replacement.

I guess that means both strategies. 🤔

**Comment by dscho** [comment]
> Using [this diff](https://lore.kernel.org/git/pull.1250.v2.git.1654778272871.gitgitgadget@gmail.com/) as an example.

That is actually a good example of a useful range-diff that is still larger than the patch itself (I think, at least) because it touches every line.

To me, this implies that there is no good "relative" measure.

Maybe a better measure would simply be the number of characters in the range-diff. Like, if the range-diff is even "only" 5kB, I would wager a bet that it is not very useful because it would be too hard to review.

> No range-diff provided. Please review the new patches as a replacement.

That would make it sound to me as if the contributor did not contribute a range-diff. Which they didn't, but that's not their fault. I would prefer something along these lines:

```
Range-diff too large. Please review it locally by calling:

  git fetch https://github.com/gitgitgadget/git <previous-tip> <current-tip>
  git range-diff <options> <previous-range> <current-range>
```

where the tips and the ranges are provided as short hashes.

**Comment by dscho** [comment]
> > where the tips and the ranges are provided as short hashes
> 
> Using `rev-parse` or just an arbitrary length? Just wondering if `rev-parse` will have all the files/hashes needed if a shallow repo is being used.

That's a good point. Maybe hard-coding a length isn't such a bad idea here.
