### ISSUE TITLE
github-glue.test.ts fails on a recent version of Node

### ISSUE THREAD

**Issue by webstech** [gitgitgadget/gitgitgadget#1111]
The test attempts a clean-up of old branches from failed tests.  It issues a delete for the branch and attempts to handle the response but the response has changed with the fetch api.

First there is an unexpected message from node:
(node:44936) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

The test fails with:
```
  ● pull requests

    expect(received).toMatch(expected)

    Expected pattern: /Reference does not exist/
    Received string:  "HttpError: fetch failed"
```

After setting `set NODE_OPTIONS=--no-experimental-fetch`  the test runs successfully.

This is not a gitgitgadget problem.  This issue is just logging there is a problem.  It will be updated as the problem gets resolved.

**Comment by webstech** [comment]
Node v18 starts to use the new http fetch api by default.  This causes a problem for @octokit/endpoint below version 7.0.2.  Found a match in [this issue](https://github.com/octokit/request.js/issues/506).  

A fresh install resolves the problem.  It also includes a lot of updates to `package-lock.json`.  A PR will be opened to update the lock file to a level that works with node 16.3, the minimum level listed in the package.json.

**Comment by dscho** [comment]
> A fresh install resolves the problem.

You mean an `npm install`? That should take `package-lock.json` into account...

**Comment by webstech** [comment]
> You mean an `npm install`?

Yes, I should have been clearer.  The octokit issue suggested that.  Too late to just try `npm upgrade --save`.

**Comment by webstech** [comment]
PR #1112 has been opened for this.
