### ISSUE TITLE
suggestion: add a `/review` action that just emails the contributor themselves..

### ISSUE THREAD

**Issue by PhilipOakley** [gitgitgadget/gitgitgadget#1133]
suggestion: add a `/review` action that just emails **just**  the contributor themselves so they (I) can see what the mailing list submission will look like. 

It would not show if cc's were wrong, but would at least allow the contributor (me) to see how they will look on the list.

Hopefully its' as simple as trimming, or substituting, the distribution list at some `tbd` place in the code.

**Comment by PhilipOakley** [comment]
> Isn't this what `/preview` does?

It (`/preview`) maybe what I asked for, but the https://gitgitgadget.github.io/ didn't mention it, so I didn't notice ;-) 

The [ReadMe](https://github.com/gitgitgadget/gitgitgadget#contributing-gitgit-patches-via-github-prs) is likewise incomplete (I usually forget to scroll down to see that doh :expressionless:.

Is there a preferred way to synchronise the sources, and include any missing actions?

**Comment by webstech** [comment]
The `WELCOME.md`, which is posted as a comment on the PR for all new submitters, does mention the `/preview` action.  Unfortunately, the feature was not made more visible to existing contributors.

**Comment by dscho** [comment]
> It (`/preview`) maybe what I asked for, but the https://gitgitgadget.github.io/ didn't mention it, so I didn't notice ;-)
> 
> The [ReadMe](https://github.com/gitgitgadget/gitgitgadget#contributing-gitgit-patches-via-github-prs) is likewise incomplete (I usually forget to scroll down to see that doh 😑.

@PhilipOakley if those places don't mention the feature, it's because nobody had time to do that yet. Seeing as you're a retiree, how about it? 😁

**Comment by PhilipOakley** [comment]
> Seeing as you're a retiree, how about it?

Retirement; It's WFH (work from home) with extra bosses and a more diverse workload :grimacing:

I see you've seen the https://gitgitgadget.github.io/ suggestion.
 I'll see if I can tweak the ReadMe as well.
 And maybe look at the Welcome.md (thanks @webstech )

**Comment by dscho** [comment]
Since we have `/preview`, I will close this ticket as "Already Done".
