### ISSUE TITLE
Can the CI run reports (esp the failed runs) include the GGG PR number?

### ISSUE THREAD

**Issue by PhilipOakley** [gitgitgadget/gitgitgadget#1134]
When a PR is forced pushed the CI will run, and hopefully pass. But often it fails e.g. `[PhilipOakley/git] Run failed: CI - Glossary_terms (e1a6b88)`.

The failure notification email does not include a reference to the original GitGitGadget PR number, even when viewing the workflow run (via the big green button in the GitHub notification email).

Is there a way of including a link back to the original GGG PR (e.g. https://github.com/gitgitgadget/git/pull/1282) in either the CI email, or (more likely) the CI's `actions/runs` page that the email links to (e.g. https://github.com/PhilipOakley/git/actions/runs/3289924117).

Any suggestions about how to make the link back to the original PR easier? (I believe I've fixed the bugs in that commit, this is more about the ease of use when joining all the capabilities through GGG)

**Comment by webstech** [comment]
Looking at the run you linked, the commit and branch are linked in the job so you may be able to determine the PR from the branch.  On the GitHub side, the run is push related and not PR related so it can't really relate them.  

<img width="317" alt="image" src="https://user-images.githubusercontent.com/7956947/197122678-949be620-01aa-4e4f-89df-46641f5f9be8.png">

The workflow could be updated to have a step determine if the current branch is used in a PR and echo out that information.  Anyone could provide a patch to do that.  Not sure of the value.  The CI runs whether there is a PR or not doesn't it?  This is a run on your repo after any push (force or not).  Sorry if I misunderstood what you are saying.

**Comment by dscho** [comment]
I agree, whatever information we can reliably get about the branch (or the PR, if the build was triggered via a PR) we already get. Sure, there might be better ways to surface that information, but that's better raised with the GitHub team via https://github.community/.

**Comment by PhilipOakley** [comment]
I've opened a discussion https://github.com/orgs/community/discussions/36905

@webstech I think there are a lot of mental model 'problems' in the workflow when using some of the cross-party tools and one can't quite tell if you've been kicked out of the flow you thought you were in. 

In retrospect (and your comments) I can see that it may be 'obvious' that everything isn't as it seems (the push triggering the CI, not GGG watching the update) and that shoelaces are easily tied together behind your back (mixed metaphor there :wink:)
