### ISSUE TITLE
Fix GitGitGadget after recent Octokit upgrade

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/gitgitgadget#1371]
There is now [a failure](https://dev.azure.com/gitgitgadget/git/_build/results?buildId=184422&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=90a03f54-a1fa-53b6-9d6f-7639fb6534d7&l=12) to fetch things:

```
Caught error Error: Global "fetch" not found. Please provide `options.request.fetch` to octokit or upgrade to node@18 or newer.:
Error: Global "fetch" not found. Please provide `options.request.fetch` to octokit or upgrade to node@18 or newer.
    at fetchWrapper (/data/gitgitgadget-agent/agent/_work/1/s/node_modules/@octokit/request/dist-node/index.js:57:11)
    at request2 (/data/gitgitgadget-agent/agent/_work/1/s/node_modules/@octokit/request/dist-node/index.js:172:14)
    at hook (/data/gitgitgadget-agent/agent/_work/1/s/node_modules/@octokit/auth-app/dist-node/index.js:364:24)
    at async set (/data/gitgitgadget-agent/agent/_work/1/s/build/script/misc-helper.js:349:28)
    at async /data/gitgitgadget-agent/agent/_work/1/s/build/script/misc-helper.js:356:9

```

The easiest (or at least most future-proof) may be to upgrade to node.js 18, but I have no idea how risky that is (what will break?)

**Comment by dscho** [comment]
@webstech could you have a look? I have very little time to look into this at the moment.

**Comment by webstech** [comment]
Can't really test but I have been running on v20 for some time now with no issues.

**Comment by webstech** [comment]
@dscho The latest jobs got:
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
Does the pipeline need to run on a more current OS?  I couldn't see where that is specified.

**Comment by dscho** [comment]
> Does the pipeline need to run on a more current OS? I couldn't see where that is specified.

I had to upgrade the VM manually (that's part of why I would love to move forward with the ideas about moving toward a GitHub workflow-based, non-stateful way to run GitGitGadget, so that we could switch to hosted runners instead of having to maintain a singleton self-hosted runner).

Things do seem to work again now.

**Comment by webstech** [comment]
Looks like there are still a couple of jobs failing - not using node 18.
Mirror Git List to GitGitGadget's PRs
Update GitGitGadget's PRs

The first one is not catching the app token failure.

**Comment by dscho** [comment]
Whoops. I forgot to mention that I adjusted the Azure Pipeline definitions.
