### ISSUE TITLE
gitgitgadget vs

### ISSUE THREAD

**Issue by parsley72** [gitgitgadget/gitgitgadget#1373]
What advantages does gitgitgadget have over [git-multimail](https://github.com/git-multimail/git-multimail)? Genuine question, I can't find a feature comparison between the two.

**Comment by dscho** [comment]
The most likely reason that nobody compared the two is that they serve totally different purposes.

git multimail sends "notification emails for pushes to a git repository".

GitGitGadget helps submitting PRs as patch submissions via mail.
