### ISSUE TITLE
Allow using GitGitGadget with PRs at https://github.com/git/git

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/gitgitgadget#146]
This came up a couple times over the past few months, and seems like a good thing to have.

Here is a rudimentary set of patches, which I plan on testing on my personal fork instead of git/git directly: https://github.com/gitgitgadget/gitgitgadget/compare/master...dscho:work-on-git.git

**Comment by phil-blain** [comment]
I see from some PR’s on git.git that GGG seems to be live there. What’s the status on this? Ready for prime time ?

I read on the list that one of the limitations of using the app on git.git was that the checks that links commits in PR’s with commits in Junio’s repo could not work there. Is this still true? Any other limitations ?

**Comment by dscho** [comment]
> I see from some PR’s on git/git that GGG seems to be live there. What’s the status on this? Ready for prime time ?

Oops, I thought that this ticket would auto-close, apparently I forgot to mention it in the PR description.

To answer your question: yep, ready for prime time.

> I read on the list that one of the limitations of using the app on git/git was that the checks that links commits in PR’s with commits in Junio’s repo could not work there. Is this still true?

Yes, that is the case. Look for example at https://github.com/gitgitgadget/git/runs/359699361. This is the check for https://github.com/gitgitgadget/git/pull/174/commits/bf9b7f897adce9a2a8316e85b504a0721afeaa35, linking that commit to git/git@90a6bb98d1.

These links are not possible on git/git, not without giving GitGitGadget write access to that repository (which we decided _not_ to).

> Any other limitations ?

Probably ;-)

One that comes to mind is that the only target branches available at git/git are `maint`, `master`, `next` and `pu`.

For https://github.com/gitgitgadget/git/pull/174, though, I wanted to target the [`js/add-p-in-c`](https://github.com/gitgitgadget/git/tree/js/add-p-in-c) branch, though. This branch is mirrored from gitster/git into gitgitgadget/git, therefore only a PR at gitgitgadget/git would ever be able to target that branch.

Thanks for the reminder, though, that this ticket is still open. I will close it now.

**Comment by phil-blain** [comment]
I noticed the ability to open PR's on git/git is not mentioned at gitgitgadget.github.io... not sure if you want to advertise it but I thought I'd let you know  :)

**Comment by dscho** [comment]
> I noticed the ability to open PR's on git/git is not mentioned at gitgitgadget.github.io...

I actually thought about this, too, but I simply lack the time to address it. PRs warmly welcome!
