### ISSUE TITLE
Preserve user timezone

### ISSUE THREAD

**Issue by thaliaarchi** [gitgitgadget/gitgitgadget#1576]
In https://github.com/gitgitgadget/gitgitgadget/pull/22 and https://github.com/gitgitgadget/gitgitgadget/pull/23, GitGitGadget was changed to use the current time when sending patches, to match `git send-email`. However, this always sends in UTC.

Would it be possible to change the timezone offset of the outgoing patch emails to match those of the corresponding commits?

**Comment by thaliaarchi** [comment]
I meant to comment here, but my interest in implementing this waned. I dug in and found, as you mentioned, that the flow is rather tightly coupled. I do have an architectural question, though. It seems that GGG has a local Git clone, that it issues Git commands to. Given that, I’m surprised so much of the info is queried from GitHub when it seems it could be fetched there. What’s the logical division of work between the clone and GitHub? (It’s likely I misunderstood something.)

Alternatively, what would you think of an optional `Tz Europe/Berlin` header that can be supplied when people care? When using a fixed timezone offset, either read from a commit or similar header, it cannot necessarily be used for future dates due to DST.

Closing this is fine with me, though, as it really hinges on me implementing this. If either approach seems feasible, I’ll file it away until the `+0000` bothers me again.

**Comment by dscho** [comment]
> It seems that GGG has a local Git clone, that it issues Git commands to. Given that, I’m surprised so much of the info is queried from GitHub when it seems it could be fetched there. What’s the logical division of work between the clone and GitHub? (It’s likely I misunderstood something.)

The plan was always to avoid having a local clone as much as possible. And in some cases, the local clone simply does not have the information we're seeking, such as: what is the GitHub handle of the author? What is the PR branch's name? Which branch does the PR target?

> what would you think of an optional `Tz Europe/Berlin` header that can be supplied when people care?

Sure, that would work.

Having said all that, I find that I have a hard time focusing on the timezone of the patches sent to the mailing list, as long as there are other issues open that seem much more pressing to me. For example, https://github.com/gitgitgadget/gitgitgadget/issues/869 and https://github.com/gitgitgadget/gitgitgadget/issues/1266 strike me much more important than the timezone in the `Date` header of the sent mails (especially keeping in mind that it is _GitGitGadget_, not you, who sends these, and as a bot, GitGitGadget is not really affiliated with any specific timezone).

**Comment by thaliaarchi** [comment]
> especially keeping in mind that it is GitGitGadget, not you, who sends these, and as a bot, GitGitGadget is not really affiliated with any specific timezone

Right, but then once it’s committed to git.git, the affiliation with GGG disappears, as there is no back-link to the email thread—only the author’s name and date and Junio’s.

I agree this isn’t the most pressing improvement to make to GGG, but I tend to think of data integrity and metadata more than most, so it was what I thought of.

**Comment by dscho** [comment]
> I tend to think of data integrity and metadata more than most

I would think that you'd be most interested in the problem that your original commits in your fork of Git have no connection on record to the commits in git/git. I find this one of the most vexing things about the mailing list-centric workflow: It is really hard to keep track of all the commits/branches/mails that should be connected automatically, but are not.

**Comment by thaliaarchi** [comment]
Well sure, but that's fundamental to the workflow and Git itself. The timezone offsets are a case where this tool is slightly lossy compared to the mail workflow, while staying compatible with the same workflow.

Incidentally, I recently read these interesting papers, that [1] determine the mailing list thread corresponding to a commit and [2] trace the flow of commits through contributers' and maintainers' repos to the blessed repo. They're hard problems, since the Git object format and protocol tracks neither. For anything contributed via GitGitGadget, [2] is easier to trace, because GitHub keeps a log of rebases and GGG shows the status. Additionally, GGG makes it easier to get to the contributor's branch in their fork, because it sends with a mailing list message ID that can be rewritten into a github.com PR URL; this is somewhat a reverse of [1].

1. Yujuan Jiang, Bram Adams, Foutse Khomh, and Daniel M. Germán. 2014. [Tracing Back the History of Commits in Low-tech Reviewing Environments: A case study of the Linux kernel](https://sci-hub.st/10.1145/2652524.2652542)
2. Daniel M. Germán, Bram Adams, Ahmed E. Hassan. 2015. [A Dataset of the Activity of the `git` *Super-repository* of Linux in 2012](https://github.com/dmgerman/papers/blob/master/2015/conferences/2015_msr_data_linux_superrepo/2015_msr_data_linux_superrepo.pdf)

**Comment by dscho** [comment]
> I recently read these interesting papers, that [1] determine the mailing list thread corresponding to a commit and [2] trace the flow of commits through contributers' and maintainers' repos to the blessed repo. They're hard problems, since the Git object format and protocol tracks neither.

GitGitGadget provides two notes refs that are designed to help with this mapping. I do have a set of shell script functions to use those refs:

```sh
# requires GitGitGadget's `commit-to-mail` notes ref
lookup_commit_to_mail () { # <commit>
        # fetch the ref if missing or older than a day
        if ! git rev-parse --verify -q refs/notes/commit-to-mail >/dev/null ||
                test $(($(date +%s)-$(git show -s --format=%ct refs/notes/commit-to-mail))) -gt 86400
        then
                echo "Fetching \`commit-to-mail\` note..." >&2
                git fetch https://github.com/gitgitgadget/git refs/notes/commit-to-mail:refs/notes/commit-to-mail ||
                die "Could not fetch 'refs/notes/commit-to-mail'"
        fi

        mid="$(git notes --ref=commit-to-mail show "$1")"
        echo "$mid"
        return 0
}

commit_to_mail () { # <commit>
        mid=lookup_commit_to_mail $1

        test -n "$mid" || {
                echo "Cannot find Message-ID for $1" >&2
                return 1
        }

        open_url "https://lore.kernel.org/git/$mid"
}
```

You can do a similar thing to do the lookup in the opposite direction, something like this:

```
mail_to_commit () { # <Message-ID>
        # fetch the ref if missing or older than a day
        if ! git rev-parse --verify -q refs/notes/mail-to-commit >/dev/null ||
                test $(($(date +%s)-$(git show -s --format=%ct refs/notes/mail-to-commit))) -gt 86400
        then
                echo "Fetching \`mail-to-commit\` note..." >&2
                git fetch https://github.com/gitgitgadget/git refs/notes/mail-to-commit:refs/notes/mail-to-commit ||
                die "Could not fetch 'refs/notes/mail-to-commit'"
        fi

        oid="$(echo "$1" | git hash-object --stdin)" &&
        git notes --ref=mail-to-commit show "$oid"
}
```
