### ISSUE TITLE
Weird character encoding issue in a Gitgitgadget comment

### ISSUE THREAD

**Issue by phil-blain** [gitgitgadget/gitgitgadget#158]
[This email](https://public-inbox.org/git/85CAC41A-A0EA-4E22-BC22-F57A59D76678@me.com/) was sent to the list and is mirrored in https://github.com/gitgitgadget/git/pull/430#issuecomment-547400942.
It seems that some characters are not showing correctly in the PR, even though the text on public-inbox looks OK.

Copy of the Gitgitgadget comment (notice the `=`, `=20`, `=C3=A0`, `=C3=A9`):

> [On the Git mailing list](https://public-inbox.org/git/85CAC41A-A0EA-4E22-BC22-F57A59D76678@me.com), Philippe Blain wrote ([reply to this](https://github.com/gitgitgadget/gitgitgadget/wiki/ReplyToThis)):
> 
> ```
> Hi Junio,
> 
> That indeed makes the trick. Thanks!=20
> Should I send a separate patch series with this patch ?  How would that =
> work ? "Signed-off by" me and "Based-on-patch-by" you ?
> 
> Philippe.
> 
> > Le 27 oct. 2019 =C3=A0 22:26, Junio C Hamano <gitster@pobox.com> a =
> =C3=A9crit :
> >=20
> > I am not sure if the compiler needs fixing in this case, but the
> > following may work it around.
> >=20
> > builtin/merge.c | 9 ++++++---
> > 1 file changed, 6 insertions(+), 3 deletions(-)
> >=20
> > diff --git a/builtin/merge.c b/builtin/merge.c
> > index e2ccbc44e2..0746f11df2 100644
> > --- a/builtin/merge.c
> > +++ b/builtin/merge.c
> ...
> ```

Copy of the text at public-inbox : 

```
Hi Junio,

That indeed makes the trick. Thanks! 
Should I send a separate patch series with this patch ?  How would that work ? "Signed-off by" me and "Based-on-patch-by" you ?

Philippe.

> Le 27 oct. 2019 à 22:26, Junio C Hamano <gitster@pobox.com> a écrit :
> 
> I am not sure if the compiler needs fixing in this case, but the
> following may work it around.
> 
> builtin/merge.c | 9 ++++++---
> 1 file changed, 6 insertions(+), 3 deletions(-)
> 
> diff --git a/builtin/merge.c b/builtin/merge.c
> index e2ccbc44e2..0746f11df2 100644
> --- a/builtin/merge.c
> +++ b/builtin/merge.c
> ...
```

**Comment by dscho** [comment]
I think the underlying cause is the same as for #139: the email you referenced looks to me as if it was encoded as "quoted-printable".

**Comment by dscho** [comment]
Closed via https://github.com/gitgitgadget/gitgitgadget/pull/160

**Comment by phil-blain** [comment]
Hi @dscho  and @webstech, I think this might not be completely fixed, here are examples of  mirrored messages with funny looking characters (`Ã©` instead of `é`, `â��` instead of `’` and of backquote, `Ã ` instead of `à`):
https://github.com/gitgitgadget/git/pull/523#discussion_r368248822
https://github.com/gitgitgadget/git/pull/523#discussion_r368245261
https://github.com/gitgitgadget/git/pull/523#issuecomment-577170547 (check Duy's name)

I have a feeling this is a different issue though...

**Comment by dscho** [comment]
> I have a feeling this is a different issue though...

I think you're right. To me, the most likely explanation is that https://github.com/gitgitgadget/gitgitgadget/pull/160/files#diff-049f3d41029ebeffaca29564949555bfR53-R56 parses the quoted-printable characters byte for byte, which does not work for UTF-8.

If you look at https://public-inbox.org/git/F2F66C31-851E-42D0-BAF7-2DE8BF0F3D72@gmail.com/raw, you will see not only that its `Content-Type` header specifies UTF-8 and its `Content-Transfer-Encoding` header says `quoted-printable`, but also that it encodes the é as `=C3=A9`. The regular expression `/=([a-fA-F0-9]{2})/` will first match `=C3` and try to convert that into a character, _then_ grab `=A9` and convert it into _another_ character.

Obviously this cannot work.

Now, if you look at https://en.wikipedia.org/wiki/UTF-8#Description, you will learn that four-byte sequences start with a byte whose top four bits are set and whose fifth bit is unset, i.e. matching `/=[Ff][0-7]`. Likewise, the three-byte sequences start with a byte whose top three bits are set and whose fourth bit is unset, i.e. matching `/=[Ee][0-9A-Fa-f]/`. For two-byte sequences, the regular expression is `/=[CDcd][0-9A-Fa-f]/`.

In all of those cases, the all subsequent bytes start with the highest bit set and the second-highest bit unset.

I fear that we will have to be quite a bit more precise in our quoted-printable decoding. Something like this should do:

```javascript
.replace(/=(/=([Ff][0-7])=([89ABab][a-fA-F0-9])=([89ABab][a-fA-F0-9])=([89ABab][a-fA-F0-9])/g, (_$0, $1, $2, $3, $4) => {
    const codePoint = ((parseInt($1, 16) & 0x7) << 18) | ((parseInt($2, 16) & 0x3f) << 12) | ((parseInt($3, 16) & 0x3f) << 6) | (parseInt($4, 16) & 0x3f);
    return stringFromCharCode(codePoint);
}).replace(/=(/=([Ee][0-9A-Fa-f])=([89ABab][a-fA-F0-9])=([89ABab][a-fA-F0-9])/g, (_$0, $1, $2, $3) => {
    const codePoint = ((parseInt($1, 16) & 0xf) << 12) | ((parseInt($2, 16) & 0x3f) << 6) | (parseInt($3, 16) & 0x3f);
    return stringFromCharCode(codePoint);
}).replace(/=(/=([CDcd][0-9A-Fa-f])=([89ABab][a-fA-F0-9])/g, (_$0, $1, $2) => {
    const codePoint = ((parseInt($1, 16) & 0x1f) << 6) | (parseInt($2, 16) & 0x3f);
    return stringFromCharCode(codePoint);
})
```

To make things really complicated, I fear that we will have to do this _only_ when the `Content-Type` header indicates that this was encoded in UTF-8.

A better alternative might be to have a local variable `decodedBody` of type `Buffer`, and to also parse the charset from the `Content-Type` header (defaulting to UTF-8), then replace the body _after_ the `for (const header of mbox.headers!)` loop via `body = decodedBody.toString(charset)`.

**Comment by webstech** [comment]
Any objection to using a package for this?  I didn't initially because the samples I found and used were simple (yes, I forgot about the multi-byte).  I see [this one](https://www.npmjs.com/package/libqp) by the nodemailer package already being used.  Tested in a private repo and it works.  Just converting the quoted numbers to binary values was a technique I saw in another package (do not use `FromCharCode`).

What do you think?

**Comment by dscho** [comment]
Sure, one more dependency won't hurt, especially if it is well used and probably safe.

**Comment by webstech** [comment]
fyi, an update on this.

I have tested with nodemailer/libqp.  Needed to create TS header file.  The libqp repo is not well set up for contributions AFAIKT.  emailed the owner (using github public id) to ask about adding the libqp.d.ts file.  Waiting for a response.  Considering adding the header to DefinitelyTyped repo.

**Comment by dscho** [comment]
Nice, thank you! From what I heard, DefinitelyTyped is the way to go when providing Typescript definitions for pure-Javascript projects.

**Comment by webstech** [comment]
DefinitelyTyped PR [43437](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43437) opened.

**Comment by webstech** [comment]
npm package @typed/libqp is now available.
