### ISSUE TITLE
GitGitGadget PR Handler pipeline is broken with a Git error

### ISSUE THREAD

**Issue by derrickstolee** [gitgitgadget/gitgitgadget#1744]
Something is broken about the GitGitGadget PR Handler pipeline.

See [this pipeline error](https://dev.azure.com/gitgitgadget/git/_build/results?buildId=227373&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=fd9d79e0-dc99-51c0-4ec1-8ae1b7984af2&l=14) (I needed to visit it anonymously to not get a strange 404 screen in the log output) for this error:

```
Starting: Pull GitGitGadget, npm install & build
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.246.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/bin/bash /data/gitgitgadget-agent/agent/_work/_temp/91495ef7-bbc2-42cf-a9e1-e0b03054b1d7.sh
From https://github.com/gitgitgadget/gitgitgadget
 * branch            main       -> FETCH_HEAD
error: update_ref failed for ref 'HEAD': cannot lock ref 'HEAD': Unable to create '/data/gitgitgadget-agent/agent/_work/1/s/.git/HEAD.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

This is blocking gitgitgadget/git#1818 from getting sent to the mailing list.

**Comment by dscho** [comment]
Sorry for the breakage! This patch series iteration is submitted now: https://github.com/gitgitgadget/git/pull/1818#issuecomment-2449086855

The build agent had gotten into a bad state, which I have fixed (there were a stale `HEAD.lock` and a stale `logs/HEAD.lock` file, both created Oct 28 19:41 UTC, and then there were corresponding lock files for the main branch that were created Oct 29 01:54 UTC, I deleted them all).

I guess this ticket provides more motivation to address #609 (which would imply a move from a self-hosted agent to hosted agents).
