### ISSUE TITLE
Node Version Needs Updating

### ISSUE THREAD

**Issue by webstech** [gitgitgadget/gitgitgadget#176]
The package.json specifies node >= 8.3.0.  Recent runs are using v10.  The latest LTS version is 12+.  v10 will go to maint mode in a few months.  There is a very good chance devs are running with a later version and may accidentally use new features.

Side note:  commander is not in the dependencies list.  Should verify if other first level dependencies have been missed.

**Comment by dscho** [comment]
> commander is not in the dependencies list.

I guess that it was originally in the dependencies of `probot-commands` or something.
