### ISSUE TITLE
GGG adds a shortlog summary instead of normal summary in order of the patch series

### ISSUE THREAD

**Issue by garimasi514** [gitgitgadget/gitgitgadget#203]
When v2 of this PR https://github.com/gitgitgadget/git/pull/497 was submitted to the Git mailing list, it included the shortlog summary of the commits included like this: 

Cheers! Garima Singh

[1] https://lore.kernel.org/git/20181009193445.21908-1-szeder.dev@gmail.com/
[2] https://lore.kernel.org/git/61559c5b-546e-d61b-d2e1-68de692f5972@gmail.com/

Derrick Stolee (2):
  diff: halt tree-diff early after max_changes
  commit-graph: examine commits by generation number

Garima Singh (8):
  commit-graph: use MAX_NUM_CHUNKS
  bloom: core Bloom filter implementation for changed paths
  commit-graph: compute Bloom filters for changed paths
  commit-graph: write Bloom filters to commit graph file
  commit-graph: reuse existing Bloom filters during write.
  commit-graph: add --changed-paths option to write subcommand
  revision.c: use Bloom filters to speed up path based revision walks
  commit-graph: add GIT_TEST_COMMIT_GRAPH_CHANGED_PATHS test flag

Jeff King (1):
  commit-graph: examine changed-path objects in pack order

This is not the same as the sequence of the patches which adds some confusion when someone is reviewing the sequence in the cover letter.

"The shortlog summary is a fine tool to show contributors to the patch
series, but is not as useful to show patch series as a whole: splitting
of patches and their ordering."
Reported-by: Jakub Narębski <jnareb@gmail.com>

**Comment by dscho** [comment]
Jakub should know that this is what `git format-patch` does, though... GitGitGadget only consumes the output, it does not generate the shortlog itself.

**Comment by dscho** [comment]
@garimasi514 I hope you don't mind that I close this as unresolved, since the issue was not raised again in the meantime? In any case, if we want to address this, it would have to be in `git format-patch`, not in GitGitGadget (or at least: first in `git format-patch`, and then, once the change trickled down to `dugite`, we may need to adjust GitGitGadget).
