### ISSUE TITLE
Is PR #164 In Use and Working?

### ISSUE THREAD

**Issue by webstech** [gitgitgadget/gitgitgadget#207]
I was researching issue #206 to understand how the different commenting functions called by `MailArchiveGitHelp::processMails` got used - ie what would cause one or another of the functions to be called.  Looking at the `lineHandler` function I got a bad feeling.  In issue #155 @dscho noted that the new lore repo updated messages and the old repo added new messages.  PR #164 did not take that into account and my research today shows a problem.  

Looking at the handle-new-emails job on [azure](https://dev.azure.com/gitgitgadget/git/_build/results?buildId=31832&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=a46d8783-b972-547c-42b9-2f94289d3941) I see a problem in the `Pull GitGitGadget` step.
```
2020-02-26T00:07:19.3325418Z From https://github.com/gitgitgadget/gitgitgadget
2020-02-26T00:07:19.3335262Z  * branch            master     -> FETCH_HEAD
2020-02-26T00:07:19.3741506Z fatal: Needed a single revision
2020-02-26T00:07:19.9218477Z fatal: Couldn't find remote ref mirror-replies-to-prs
2020-02-26T00:07:19.9257460Z fatal: ambiguous argument 'FETCH_HEAD': unknown revision or path not in the working tree.
```

The `linehandler` function probably needs to only buffer lines starting with /[ +]/.  The use of counter hitting zero will also need to change to handle common lines after the changed lines.

Am I misinterpreting this?

**Comment by dscho** [comment]
> Looking at the handle-new-emails job on [azure](https://dev.azure.com/gitgitgadget/git/_build/results?buildId=31832&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=a46d8783-b972-547c-42b9-2f94289d3941) I see a problem in the `Pull GitGitGadget` step.
> 
> ```
> 2020-02-26T00:07:19.3325418Z From https://github.com/gitgitgadget/gitgitgadget
> 2020-02-26T00:07:19.3335262Z  * branch            master     -> FETCH_HEAD
> 2020-02-26T00:07:19.3741506Z fatal: Needed a single revision
> 2020-02-26T00:07:19.9218477Z fatal: Couldn't find remote ref mirror-replies-to-prs
> 2020-02-26T00:07:19.9257460Z fatal: ambiguous argument 'FETCH_HEAD': unknown revision or [...]
> ```

This is caused by this part of the Azure Pipeline:

```sh
# If the public-inbox handler is not yet in master, use Dscho's branch
git rev-parse --verify FETCH_HEAD:lib/public-inbox-helper.ts ||
git fetch https://github.com/dscho/gitgitgadget mirror-replies-to-prs
```

I.e. it is a _really_ stale left-over from previous times where I wanted to get things into the Pipeline even before the PR was merged ;-)

I have disabled that code.

**Comment by webstech** [comment]
The lore repo only has one object that keeps getting updated.  It looks like `MailArchiveGitHelp::processMails` maybe needs to use `git log --raw` to get the object ids and then use `cat-file` to print the objects.  Is there a better way to do this?

**Comment by dscho** [comment]
@webstech I think you're right, and we should handle only the `+` lines in https://github.com/gitgitgadget/gitgitgadget/blob/3b6bf4cdc3844dbed3442c424fd9e11e6f428edb/lib/mail-archive-helper.ts#L178. I.e. something like

```diff
-if (counter)
+if (counter && line.substr(0, 1) === "+")
```

**Comment by webstech** [comment]
@dscho In theory we need the unchanged lines as well and diff does not give all of them.  That is why I suggested using cat-file.

**Comment by dscho** [comment]
True. We would need `line.substr(0, 1).match(/[ +]/)` instead.

The problem with `cat-file` is that it would take quite a bit of spawning processes, i.e. it would not be fast.

I propose instead to increase the context to an insanely high number (`git log -U99999`). That way, we most likely get all the lines.

**Comment by dscho** [comment]
I _guess_ that it sort of worked, by looking at pretty much all the `-` lines instead of the `+` lines. Which means that it did not look at the newest mail in lore, but always at the second-to-newest one...

**Comment by webstech** [comment]
> I _guess_ that it sort of worked, by looking at pretty much all the `-` lines instead of the `+` lines. Which means that it did not look at the newest mail in lore, but always at the second-to-newest one...

Are you testing changes?  Just trying to avoid both of us working on the same problem.  Sorry this was not fixed in pr #164.  The change in how the two repos worked did not click with me then.

I will also be looking at how to create some tests for the `handle-new-emails` command.

**Comment by webstech** [comment]
@dscho I wasn't sure why you were working with `-` versus `+`.  I have pushed an update to my eslint branch that appears to work.  It has diagnostics in it but I wanted to get it in front of you in case you want to take the changes.  The azure job is broken so getting a code fix is a priority before setting the variable.

**Comment by webstech** [comment]
Reran and `seen` in `mboxHandler` is not kicking out old messages.  Not sure why and too late to figure it out.  Something to watch for - do not want to post comments to old PRs.  Looking some more tomorrow.

**Comment by webstech** [comment]
`this.state.latestRevision = "3b38d8d206c64bf3dc873ba8ae9dbd48ed43f612";`
This should really be the commit where `handle-new-emails` started being used.  There are lots of 'comments' for PRs in the lower numbers.  Should there be a minimum PR#?

Sadly it is tomorrow. 😣

**Comment by dscho** [comment]
@webstech thanks for pointing out the broken Pipeline. I have hence fixed it (see #208), with some minimal changes to the code.

To be honest, I think that the transition code was (is) broken, and that it was the reason why I had to scramble to get things working again. In my tests, the code actually did what it was supposed to do, but I had way too little logging to see whether it was actually triggered or not. My guess is that it was not triggered. The good news is that we don't need that code anymore: the transition is done.

**Comment by dscho** [comment]
Oh, and to answer the question: #164 was only _partially_ in use and working. Unfortunately not in the part that calls `processMails()`... but with #208, that should be now fixed.

**Comment by dscho** [comment]
> Reran and `seen` in `mboxHandler` is not kicking out old messages.  Not sure why and too late to figure it out.  Something to watch for - do not want to post comments to old PRs.  Looking some more tomorrow.

I think my reasoning was that even closed PRs sometimes get replies, even after years "in production". I have been known to dig out the underlying reasons for hard-to-debug issues, too, and then reply to the original mails.

Maybe we can keep this behavior?

I mean, it does not quite hurt anything. That `git ls-tree -r <notes>` call finishes in under a second for me, and it lists almost ten thousand objects (which are the hashed Message-IDs). That's not too bad, is it?

**Comment by webstech** [comment]
> Maybe we can keep this behavior?

Sure.  My problem was running with `this.state.latestRevision = "3b38d8d206c64bf3dc873ba8ae9dbd48ed43f612";` - the start commit and not the latest from public inbox repo.  It precedes the creation of the tracking notes so all the early messages that were not posted to github were not `seen` (ie git pull #3).  The code wanted to create github comments for these.

> I mean, it does not quite hurt anything. That `git ls-tree -r <notes>` call finishes in under a second for me, and it lists almost ten thousand objects (which are the hashed Message-IDs). That's not too bad, is it?

It won't hurt anything as long as `state.latestRevision` is valued.  Would have to have messed something up for it not to be valued.

**Comment by dscho** [comment]
> My problem was running with `this.state.latestRevision = "3b38d8d206c64bf3dc873ba8ae9dbd48ed43f612";` - the start commit and not the latest from public inbox repo. It precedes the creation of the tracking notes so all the early messages that were not posted to github were not `seen` (ie git pull #3). The code wanted to create github comments for these.

I am not sure I understand... could I ask for clarification?

**Comment by webstech** [comment]
> I am not sure I understand... could I ask for clarification?

I'll try but I have been told I'm not very good at it. 🙄  Running with the initial `state.latestRevision` (vs the current value in the repo) will pick up emails that do not have notes/github PR comments.  There are lots emails (>1000) that get trace messages like this:
```
Message-ID 6b7a50dc-6b71-0e31-030a-42dd1b26bde4@ramsayjones.plus.com 450706c41c0b09fec745001817f4ea6d21636ba2 (length 3060) for PR https://github.com/gitgitgadget/git/pull/10, commit undefined, log commit 4b294de31f17b2d8bd9c52b645b2561e0fabd8a4, comment ID: undefined
```

Most of these are from before `handle-new-mails` was implemented.  The number of missed emails goes down when the PR# is >200 but not sure why the later ones are missed.  I looked at a couple and the email is definitely not in the github pr comments.  For example,
`References: <pull.368.git.gitgitgadget@gmail.com>` is in lore commit `b79bd1e802f2960d16ceda4cf9d28de69883448a` but the email is not in PR #368.

I can provide a log of this if you are interested.

**Comment by dscho** [comment]
> Running with the initial `state.latestRevision` (vs the current value in the repo) will pick up emails that do not have notes/github PR comments.

Oh, you mean https://github.com/gitgitgadget/gitgitgadget/blob/3b6bf4cdc3844dbed3442c424fd9e11e6f428edb/lib/mail-archive-helper.ts#L194-L200

This is just historical, and should actually never be hit because GitGitGadget always auto-updates the `gitgitgadget` note in the Git worktree before running this, right?

In other words, I would not worry about that at all. Some of the code is pretty historical and could probably be removed. In this instance, I guess `throw new Error("No latestRevision in the GitGitGadget note?!?!?");` would make more sense than using this arbitrary commit (that is a public-inbox commit anyway, right?).

Likewise, the code to help the transition from public-inbox to lore (which seemed to not quite work...) can be removed now. There is only one agent currently, and it made the switch. In the unlikely case that I have to stand up a new agent, it will be initialized with a lore-git repository and the GitGitGadget note will already reference a commit within that repository.

**Comment by webstech** [comment]
> This is just historical, and should actually never be hit because GitGitGadget always auto-updates the gitgitgadget note in the Git worktree before running this, right?

I needed a start point because the Git worktree `state.latestRevision` was still pointing to the old archive and I was being too lazy to configure the migration path.  Tests would have run a lot faster if I had selected a later commit from the lore repo but I would not have learned as much.

> In this instance, I guess throw new Error("No latestRevision in the GitGitGadget note?!?!?"); would make more sense than using this arbitrary commit (that is a public-inbox commit anyway, right?).

I agree on throwing an error.  There is a commit in the lore repo with this hash.

Thanks for getting this fixed.

**Comment by dscho** [comment]
> but I would not have learned as much.

😀 

> > In this instance, I guess throw new Error("No latestRevision in the GitGitGadget note?!?!?"); would make more sense than using this arbitrary commit (that is a public-inbox commit anyway, right?).
> 
> I agree on throwing an error.

:+1:

> There is a commit in the lore repo with this hash.

Oh, I must have converted it, then...

Can we close this ticket at this point? I.e. has your concern been addressed adequately?

**Comment by webstech** [comment]
> Can we close this ticket at this point? I.e. has your concern been addressed adequately?

Yes and yes.  Nothing like looking at code and getting that sinking feeling in your gut as you realize it is broken.

**Comment by dscho** [comment]
Hey, on the bright side, it's fixed now!
