### ISSUE TITLE
How to support manual tests

### ISSUE THREAD

**Issue by webstech** [gitgitgadget/gitgitgadget#213]
Looking for input on adding manual single run tests.  I may have missed it but Jest does not seem to have an easy solution.  Searching around I have not found other simple solutions.  Files excluded with jest.testregex can not be re-added by being named on the command line.

Possible solutions:

- Use a separate config.  This would require a `npm run test:dev` target (or similar) and duplication of other config info.
- Add state detection to the test case (ie check for git config values).  This makes the test code a little uglier compared to other test cases.

Looking for experience from other projects - a separate config seems popular with a different `testRegex`.

**Comment by dscho** [comment]
For manual testing, I usually patch `misc-helper.ts` and run it via `ts-node`, outside Jest.

Why do you want to run them in Jest?

In any case, I would have thought that a separate directory would support that use case better, I'm sure there is a way e.g. in VS Code (overriding the config).

**Comment by webstech** [comment]
> Why do you want to run them in Jest?

The tests are still testing specific functions (`GitHubGlue` in this case) and using `expect`.  Currently set up to run actual test if configured for it. See the test [here](https://github.com/gitgitgadget/gitgitgadget/commit/2bc2bd6d41fa45179cd1e378c190a01e25143648).

> In any case, I would have thought that a separate directory would support that use case better, I'm sure there is a way e.g. in VS Code (overriding the config).

The test will run successfully even if it has not been configured so it could be part of the regular tests and only happens for those who have it configured.  It looks like a separate config (or no config) is needed to run in a separate dir from my testing so far.  The pathing in the default config seems to still apply when specifying tests on the command line.

**Comment by dscho** [comment]
Okay, thank you for the clarification!

**Comment by webstech** [comment]
Closing this.  The solution appears to be a separate directory (probably under `tests`), config and target in package.json.  An example use case would be for a linting test to run tests against a number of existing git commits when a change is made to any of the linting rules.  Not needed to run on a regular basis but could be useful if making a change.
