### ISSUE TITLE
GitHub Security Alerts

### ISSUE THREAD

**Issue by webstech** [gitgitgadget/gitgitgadget#217]
Is there any concern with doing a large update to remove the two security alerts?  npm outdated showed a number of out of date packages.  This is the results of an npm update:
    "@types/jest": "^25.1.4",
    "@types/jsonwebtoken": "^8.3.8",
    "@types/marked": "^0.7.3",
    "@types/nodemailer": "^6.4.0",
    "jest": "^25.2.4",
    "jest-junit": "^10.0.0",
    "ts-jest": "^25.3.0",
    "ts-node": "^8.8.1",
    "tslint": "^5.20.1",
    "typescript": "^3.8.3"
  "dependencies": {
    "@octokit/auth-app": "^2.4.4",
    "@octokit/rest": "^17.1.4",
    "commander": "^5.0.0",
    "dugite": "^1.88.0", <== already done!
    "html-to-text": "^5.1.1",
    "jsonwebtoken": "^8.5.1",
    "marked": "^0.8.2",
    "nodemailer": "^6.4.6",

I can do nodemailer separately because it requires a code change.  The others could be broken up but do they need to be?

**Comment by dscho** [comment]
I'd say that our test suite is now comprehensive enough that we can do a bulk update. :-)

**Comment by webstech** [comment]
PR #222 opened to start this.  

In 'dll-hell' on the other updates.  Initial tests a week ago looked good.  Today, had to specifically install a couple of levels back on a supporting package.  Compile errors on the most recent versions.
`npm i @octokit/types@2.5.1`  _<rant>There are a bug issues for both recent releases - not clear why a second release was done when a breaking bug had been found.</rant>_

tslint also took an error I did not notice a week ago that required a tslint.json change.
`"array-type": [true, "array-simple"]`
Still researching.  Updating tslint.json solved the issue but not sure why it is new.  Also, there is the conversion away from tslint that may make this mute.

**Comment by dscho** [comment]
Thank you for keeping on the ball!

**Comment by webstech** [comment]
PR #223 opened to address the second phase of this.

**Comment by dscho** [comment]
You're the best!

**Comment by webstech** [comment]
Thanks.  Maybe a little overstated. 🤣  Appreciate your comments.
