### ISSUE TITLE
Name and address on the From: header of e-mail coming from GGG is misleading

### ISSUE THREAD

**Issue by gitster** [gitgitgadget/gitgitgadget#228]
It seems that GGG places <gitgitgadget@gmail.com> as the sender address and "Commit Author Name via GitGitGadget" as the human-readable name for the sender.

This has a few drawbacks.

 - Because the real commit author name is never with "via GitGitGadget", this arrangement forces all patches to have in-body From: that records the real author name. This redundancy does not add any value to reviewers, as we humans know how to strip out "via GitGitGadget" anyway.

 - When sending out a multi-patch series with multiple authors, each patch is sent with "From: " header taken from the commit author name. There is *no* clue, other than in the cover letter, that tells who created a pull request to trigger GGG,

Can we fix these by doing a few simple changes, perhaps?

 - Record the user who did the pull request on the "From:" header of cover letter and patches in the series.
 - Keep adding in-body From: as necessary to record the commit author name when it is different from the user who created the pull request (whose name and address is recorded on the "From:" header of the e-mail).
 - Use "Sender:" to record the fact that the message is sent from <gitgitgadget@gmail.com> instead.  Add the same on "Cc:" if needed to ensure that responses will be seen by GGG.

See https://lore.kernel.org/git/pull.622.git.1588347029.gitgitgadget@gmail.com/ for an example of a topic that has multiple authors.

Thanks.

**Comment by dscho** [comment]
Are we sure that such a mail would not be filtered out by vger and/or subscribers of the Git mailing list? That is, and was, my biggest concern when I came up with the `via` strategy.

**Comment by gitster** [comment]
I manually added "Sender: (redacted)@pobox.com" to send out https://lore.kernel.org/git/xmqqpnbg6gfv.fsf_-_@gitster.c.googlers.com/raw and it seems to have reached lore.kernel.org/git/ archive.

**Comment by gitster** [comment]
Any progress on this?

**Comment by dscho** [comment]
> Any progress on this?

Sorry, no, I am swamped and short on time :-(

**Comment by webstech** [comment]
There is an edge case where the author of the pull request does not have a public email on github and is not the author or contributor to any of the patches.  The sender email would be unknown.  In that case, how should the `From:` be done?  Should the existing `via GitGitGadget` format be used (with ggg email) or just show the name with no email address?  I think I prefer the latter but could it be a problem for some mail agents?  There would still be the `Sender:` header that some agents show as  `From:`.

I am not sure we have seen this happen yet.  There would be a `no public email` message in the `/submit` response comment.

**Comment by dscho** [comment]
> There is an edge case where the author of the pull request does not have a public email on github and is not the author or contributor to any of the patches.

I am not sure that I want such an author to submit patches on others' behalf. In my mind, when somebody submits patches on someone else's behalf, all future feedback needs to go to the submitter, and it is the submitter's responsibility to take care of it. And without an email address, that's not possible.

Of course, right now, we allow such a thing. That does not necessarily make me happy...

**Comment by webstech** [comment]
> Of course, right now, we allow such a thing. That does not necessarily make me happy...

I have not looked at all PRs but the warning of no/invalid email on the initial PR may be having an effect - it appears to get cleaned up.  I would have no problem requiring an email for a `/submit` to run - `/preview` requires it.  Requiring an email address may not make you happy but it may make you less unhappy. Me too.

**Comment by webstech** [comment]
Forgot to mention pr #296 was opened for this and it was reverted by pr #301.

The nodemailer doc does state that gmail will always set the sender to the gmail account.  It is not clear if multiple entries in the `from:` header (PR requester and ggg) will work.  Will try to run a test.

Changing smtp servers does not appear to be workable either.  Some services will send a validation email to the PR requester before sending the email.  The smtp servers will use DKIM and SPF for security.  These are DNS records, so a gmail account can not be used.

**Comment by dscho** [comment]
> * Use "Sender:" to record the fact that the message is sent from [gitgitgadget@gmail.com](mailto:gitgitgadget@gmail.com) instead.  Add the same on "Cc:" if needed to ensure that responses will be seen by GGG.

Alas, I think that it is https://en.wikipedia.org/wiki/Sender_Policy_Framework that disallows us from doing that, and lets GMail simply replace the email address in the `From:` header by GitGitGadget's, adding a pretty useless `X-Google-Original-From:` header.

And I don't really think that we _can_ solve this (even by trying to find a different mail provider), as SPF is an important safeguard against spamming and I do not want GitGitGadget to undermine it.

**Comment by dscho** [comment]
I still have the impression that this ticket simply _cannot_ be addressed without violating SPF.
