### ISSUE TITLE
Automatically add a Cc: when seeing a reply on the Git mailing list

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/gitgitgadget#229]
Whenever somebody on the Git mailing list replies to a patch or cover letter, chances are that they want to see the next iteration of it. It would be wonderful, therefore, if GitGitGadget could automatically add them to the `Cc:` footer (adding one if necessary) unless they were already mentioned in said footer.

**Comment by phil-blain** [comment]
Ideally, with a message from the bot on the PR saying "I updated the CC list", I guess ?

**Comment by dscho** [comment]
> Ideally, with a message from the bot on the PR saying "I updated the CC list", I guess ?

Good idea!

**Comment by dscho** [comment]
While at it, a `/cc` command would probably not hurt, either. This will need to be implemented in [`handleComment()`](https://github.com/gitgitgadget/gitgitgadget/blob/e8ec25f755cc0b770ba956e2932f45b4d0fe0e03/lib/ci-helper.ts#L545-L675). The idea would be to add a new method to the [`GitHubGlue` class](https://github.com/gitgitgadget/gitgitgadget/blob/main/lib/github-glue.ts) to retrieve the first comment, append a footer, and the update the first comment with the new contents.

This would also require adjustments in [the Azure Function](https://github.com/gitgitgadget/gitgitgadget/blob/ea28da81c344566624941a7e496b09aba5515485/azure-function/index.js#L142).

By virtue of having a single agent in the agent pool used by GitGitGadget's PR handler, we do not really have to worry about concurrent edits. Or maybe we do, as PR authors could edit the comment manually at the same time?

**Comment by webstech** [comment]
PR #297 has been opened to address the first part of this.  A separate PR will be done for the `/cc` command after the PR gets accepted.

The question about concurrent updates has not been addressed.

**Comment by dscho** [comment]
Fixed via #297

**Comment by webstech** [comment]
PR #306 has been opened to add the /cc command.
