### ISSUE TITLE
 Cover letters are hard to read on the mailing list (break lines?)

### ISSUE THREAD

**Issue by stefanbeller** [gitgitgadget/gitgitgadget#26]
Observation:
https://github.com/gitgitgadget/git/pull/1 is easy to read the cover letter, whereas https://public-inbox.org/git/pull.1.v4.git.gitgitgadget@gmail.com/ is not easy to read.

Research suggests, that it makes it easier to read when lines are broken early
https://baymard.com/blog/line-length-readability

So maybe the GGG could break lines (80 chars ?) before sending out the test to the mailing list.
After thinking about it, I found it too hard to just send a pull request, as for example we would not break
lines in code quotes or other markups, whereas regular text would want to enjoy being broken short.

**Comment by dscho** [comment]
The funny thing is that I already started this in 8556d38bd0fe598f45c4b2d42af83c878ded6b45, but completely forgot that I had not finished it...
