### ISSUE TITLE
Comparison to submitgit

### ISSUE THREAD

**Issue by sschuberth** [gitgitgadget/gitgitgadget#28]
As a user of https://github.com/rtyley/submitgit I'd be curious why I should use *gitgitgadget* instead. So how about outlining the differences / motivation to create *gitgitgadget* as part of `README.md`?

**Comment by dscho** [comment]
> As a user of https://github.com/rtyley/submitgit I'd be curious why I should use gitgitgadget instead.

You shouldn't. If you are happy with SubmitGit, by all means, stick to it.

> So how about outlining the differences / motivation to create gitgitgadget as part of README.md?

There are three issues with SubmitGit that I could not overcome:

- SubmitGit requires users to essentially give their email credentials away to Amazon. A few contributors offered strong objections to that.
- SubmitGit is not really integrated into GitHub, and as a consequence it has a separate user interface, and no way whatsoever to do more than just translating a set of commits into mails that are then sent off to the list. Things like mentioning on the PR when a patch made it into the `pu` branch, or closing the PR when the patch was accepted into `master`, are plainly impossible with SubmitGit, let alone sending updates to the PR when the corresponding branch was mentioned in the "What's cooking" mails (see also https://github.com/gitgitgadget/gitgitgadget/blob/master/TODO.md#tasks-that-would-be-really-nice-to-have-too-time-permitting for more things that GitGitGadget was designed to allow).
- SubmitGit, as nicely as it might be written, has a rather large hurdle of being written in pretty idiomatic Scala. I am not a regular Scala programmer. I don't even *like* Scala. I am totally unfamiliar with the frameworks that were used, and there is no document that helps me with getting started to develop, test, add tests, and what IDE I should use. Typescript is so similar to Javascript, and has the obvious integration into VS Code, that I chose it over any other language. Besides, the Probot framework is already available as node.js module, and rumors have it that it will be ported to Typescript, too.

There is a host of more information about motivations and design goals in the `TODO.md` and the `DESIGN.md` files (and some of those are inverse to SubmitGit's).

Feel free to contribute a PR if you care enough.
