### ISSUE TITLE
Warn if email in CC list is unreachable

### ISSUE THREAD

**Issue by phil-blain** [gitgitgadget/gitgitgadget#289]
In https://github.com/gitgitgadget/git/pull/691 I added Philip Oakley to the CC list, with his email taken from the CC list in [this message](https://lore.kernel.org/git/CACsJy8ADj-bTMYDHxRNLOMppOEdPbVwL49u3XCfNBCmoLLZo+A@mail.gmail.com/). 

Apparently this email account does not work anymore, but I was not made aware of that by Gitgitgadget, I realized it when I received a "Mail Delivery Failure" email when I replied-all from my email client to a comment on my series.

I think it could be nice if GGG could add a comment on the PR if one of the emails in the CC list is unreacheable. I guess that would mean monitoring the emails sent *to* the GGG Gmail address, which may or may not be feasible. I'm just throwing the idea out there.

[Meta question]: apart from manually checking the most recent commit for each person in the CC list with `git log -1 --author '<some person>'` upstream/master, is there a builtin way in Git to check the "currently in-use" email address of someone ?

**Comment by dscho** [comment]
> I think it could be nice if GGG could add a comment on the PR if one of the emails in the CC list is unreacheable. I guess that would mean monitoring the emails sent _to_ the GGG Gmail address, which may or may not be feasible. I'm just throwing the idea out there.

This is an interesting idea. We could use IMAP to find new MAILER-DAEMON mails that have not yet been handled, and maintain a list of email addresses known to bounce.

An interesting idea, but to be sure, not a trivial one to implement, given that there is no standardized way to indicate that an email address bounced (as opposed to replying with a "full mailbox" or a "you are graylisted and need to send this again").

@phil-blain do feel free to play with this idea, it would be great to have it!

> [Meta question]: apart from manually checking the most recent commit for each person in the CC list with `git log -1 --author '<some person>'` upstream/master, is there a builtin way in Git to check the "currently in-use" email address of someone ?

This is indeed the most natural way to check for that, although there are always [contributors who go out of their way to complicate things](https://lore.kernel.org/git/87eeolo9v9.fsf@linux-m68k.org/).

Having said that, in general it is possible, and I am using this alias (courtesy of @peff):

```ini
[alias]
	who = !sh -c 'git --no-pager -c mailmap.blob=origin/master:.mailmap log -1 --format=\"%aN <%aE>\" --author=\"$1\" -i origin/master' -
```

**Comment by phil-blain** [comment]
Thanks for the alias, here is my variant in case it can be useful for lurkers:
```bash
git config --global alias.who '!f () { git --no-pager -c mailmap.blob=upstream/master:.mailmap log -1 --format="%aN <%aE>" --author="$1" -i upstream/master;  }; f'
```

**Comment by dscho** [comment]
> @phil-blain do feel free to play with this idea, it would be great to have it!

Did you get a chance yet?

**Comment by phil-blain** [comment]
Oh, this is too far from what I know to be able to come up with something useful in any reasonable time frame, I would say.

**Comment by dscho** [comment]
Shall we close, then?
