### ISSUE TITLE
Improve documentation around single-patch contributions

### ISSUE THREAD

**Issue by phil-blain** [gitgitgadget/gitgitgadget#340]
Single patch contribution do not need a PR description, apart from the eventual "CC:" and "Changes since vX" for further iterations.

What usually happens is that the commit message is pasted as-is in the PR description by the contributor, so it appears twice on the mailing list (the first time as the commit message and the second time below the '---' as the in-patch commentary". This increases the signal-to-noise ratio for reviewers.

Maybe we could add a note about that in the GGG documentation:
- On the GGG home page
- In the greeting message posted by GGG in the PR for new contributors
- in MyFirstContribution

**Comment by webstech** [comment]
> What usually happens is that the commit message is pasted as-is in the PR description by the contributor

Doesn't GitHub do this when the PR is opened?  ie, no action by the contributor.  GGG does remove the new user welcome message if it is left in the description.

If the description matches the commit message then maybe it could be removed/not added.  Would need to allow for signed-off being present or not.  I often remove signed-off and line-ends so that could present more matching issues.

**Comment by dscho** [comment]
> > What usually happens is that the commit message is pasted as-is in the PR description by the contributor
> 
> Doesn't GitHub do this when the PR is opened? ie, no action by the contributor. GGG does remove the new user welcome message if it is left in the description.

That is the case for multi-patch contributions. But for single-patch contributions, the commit message is pasted in.

> If the description matches the commit message then maybe it could be removed/not added.

I briefly looked into this a while ago, but gave up after discovering that

1. the way GitHub (re-)formats the commit message might be different enough from the original that it is hard to detect, and
2. at the point where GitGitGadget inserts the cover letter, we do not have easy access to the original commit message to begin with, it would have to be retrieved manually.

> Would need to allow for signed-off being present or not. I often remove signed-off and line-ends so that could present more matching issues.

Indeed.

**Comment by webstech** [comment]
> > > What usually happens is that the commit message is pasted as-is in the PR description by the contributor
> > 
> > Doesn't GitHub do this when the PR is opened? ie, no action by the contributor. GGG does remove the new user welcome message if it is left in the description.
> 
> That is the case for multi-patch contributions. But for single-patch contributions, the commit message is pasted in.

I was trying to clarify the commit message is pasted in by GitHub and not the contributor.

If users `/submit` a single patch with no description, would need to make sure the automated cc feature still works.

**Comment by dscho** [comment]
Addressed by https://github.com/git/git/pull/1665
