### ISSUE TITLE
github-glue.test.ts Is Not Working

### ISSUE THREAD

**Issue by webstech** [gitgitgadget/gitgitgadget#348]
PR #341 changed some config variable names to camel case.  The names in question are three part names.  The `git config` command documentation states part 2 (subsection) is case sensitive.  The case sensitivity must have historical reasons for existing (the other parts are case insensitive).  The tests need to use config variable names that work easily for testers or clearly document the name casing requirements.

**Comment by webstech** [comment]
Just to clarify, `gitgitgadget.gitHubTest.gitHubUser` is the only variable name in question.  Other three part names use the value of this variable.  The case sensitive subsection is a quirk but it needs to be handled.

**Comment by dscho** [comment]
Sorry for the breakage, you're absolutely correct!

**Comment by dscho** [comment]
Hmm. On further consideration, the pronunciation of GitHub is /ɡɪthʌb/, not /ɡɪθʌb/. Therefore, I think the original spelling was wrong, and I would prefer to require an update to the test setup... (and I think there is only one such setup: yours 😉)

**Comment by webstech** [comment]
I don't disagree.  Changing `gitgitgadget.gitHubTest.gitHubUser` to `gitgitgadget.CIGitHubTestUser' is more consistent with other test config vars and removes the case issue.  Are you okay with that?

Related to this, are you interested in setting up ggg to support these optional tests?  It would provide more complete testing when dependabot is pushing updates.  Two things to set up and configure:
1. email tester such as ethereal for sending emails
2. dummy repo for testing the github api.

**Comment by dscho** [comment]
> Changing `gitgitgadget.gitHubTest.gitHubUser` to `gitgitgadget.CIGitHubTestUser' is more consistent with other test config vars and removes the case issue. Are you okay with that?

Of course!

> Related to this, are you interested in setting up ggg to support these optional tests? It would provide more complete testing when dependabot is pushing updates. Two things to set up and configure:
> 
>     1. email tester such as ethereal for sending emails
> 
>     2. dummy repo for testing the github api.

I am all for it, but how would we see problems in the sending emails stage? AFAIU this has to be checked manually.

**Comment by webstech** [comment]
> I am all for it, but how would we see problems in the sending emails stage? AFAIU this has to be checked manually.

The test cases do check for the email `Submitted as` message, so any failures with nodemailer would get caught.  May take a look at the tests at some point to see if there is specific email content to be checked.

**Comment by dscho** [comment]
Maybe we could extend the tests so that they look at the website to see whether the mail arrived, if not, wait for a couple seconds, then try again, and repeating until either a timeout has been reached or the mails have been seen?

**Comment by webstech** [comment]
> Maybe we could extend the tests so that they look at the website to see whether the mail arrived, if not, wait for a couple seconds, then try again, and repeating until either a timeout has been reached or the mails have been seen?

For a fun exercise I am trying that using `imap-simple`.  This could allow actual verification of  content/headers.  Looks promising except we may not be able to use tls.

**Comment by dscho** [comment]
Excellent idea. I just don't understand why we cannot use `imap-simple`?

**Comment by webstech** [comment]
> Excellent idea. I just don't understand why we cannot use TLS?

TLS may work on the server - will probably find out tomorrow when a prototype is pushed.  Locally there are cert issues similar to running a web server.  Need to re-familiarize myself with the issues.
