### ISSUE TITLE
How to "amend" a pull request?

### ISSUE THREAD

**Issue by ugultopu** [gitgitgadget/gitgitgadget#468]
Sorry I had to create an issue, since the GitHub discussions are not enabled on this repository.

I have created a [pull request](https://github.com/git/git/pull/969) and submitted a patch. It received some comments and hence, I amended the single commit on my pull request and force pushed it to my branch.

What should I do now? Should I just add another comment `/submit` on the pull request? Will this create a new patch or will it reply to the email on the mailing list?

What is the correct action now?

**Comment by ugultopu** [comment]
I just added `/submit`. I think that was the correct thing to do.

**Comment by dscho** [comment]
It was the correct thing to do.
