### ISSUE TITLE
Improve `Cc:`ing

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/gitgitgadget#58]
We should *always* Cc: the Submitter. To that end, we need to record email addresses of the people allowed to use GitGitGadget (i.e. extend `/allow` to try to figure out a public email on GitHub, and if there is none, require one to be provided in the same `/allow` command, extending the syntax to `/allow Name Of Submitter [<email@address>]`).

While at it, `/allow` could also get the feature where calling it without argument automatically uses the owner of the PR as the user to add.

**Comment by webstech** [comment]
Pull request #101 will default /allow to the owner of the PR.

I am not sure GitGitGadget should retain the email address.  It could just get it from github each time.  GitHubGlue::getGitHubUserInfo(login: string): Promise<IGHUser> (see issue #94 for interface) could replace getGitHubUserName use in CIHelper.  That would support the user changing/adding a public email address in github.

If someone does not have a public email address, they probably do not want to provide a private one to GitGitGadget and have it publicly available.  Considering how easy it is to have a throw away email address I wonder how many users do not have a public email address.  What GitGitGadget could do when the PR is opened is add a comment if the PR author does not have a public email.  The author can then make the choice to add one or not.  They can remove it from their profile after the PR is closed if they want.  That would still leave the email public in the repo but not as obvious as looking at a user profile.

**Comment by dscho** [comment]
> I am not sure GitGitGadget should retain the email address. It could just get it from github each time.

My experience is that it is not public most of the time, and even the real name is not part of the public information. So I really would like to have a `.mailmap`-like record of mappings between the GitHub account name and the "Real Name <email@address>" information.

> If someone does not have a public email address, they probably do not want to provide a private one to GitGitGadget and have it publicly available.

True. I know of one such case. The problem with that is that Git does not accept such contributions. The real name and a working email address is required for the DCO to be remotely valid.

**Comment by webstech** [comment]
> I really would like to have a `.mailmap`-like record of mappings between the GitHub account name and the "Real Name [email@address](mailto:email@address)" information

Having a separate copy means providing a method to update (yes, I know, disallow/allow but someone has to remember to do it).  On the other hand, if GitGitGadget just refused to submit requests without a public email in github, the github info can be used.  It would make it simpler to allow the user to change the email (and name) by using a single source.  Is the github public email always an address verified by github?

What do you think?

**Comment by dscho** [comment]
Good points.

We should probably test in the `/allow` command, then, that there is a public email address and that there is a Real Name to use, too, and to mention this as a warning in the comment that is added.

Sound good?

**Comment by dscho** [comment]
>  Is the github public email always an address verified by github?

AFAIR yes, I had to click a verification link in a mail last time I added an email address.

**Comment by dscho** [comment]
Thank you @webstech!!!
