### ISSUE TITLE
Fix duplicate mail headers

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/gitgitgadget#74]
As @sunshineco mentioned [here](https://github.com/gitgitgadget/gitgitgadget/pull/56#commitcomment-31781797) and [here](https://github.com/gitgitgadget/gitgitgadget/pull/55#commitcomment-31781797), there should be at most one `Content-Description:`, `Content-ID:`, `Content-Type:` and `Content-Transfer-Encoding:` header, [just like the `MIME-Version` header](https://github.com/gitgitgadget/gitgitgadget/pull/55).

**Comment by sunshineco** [comment]
Thanks for opening this ticket. I was just wondering the other day if #38 should be re-opened, but opening a new ticket makes more sense.

**Comment by webstech** [comment]
I have a proposed fix on the DupMailHdrs branch of my project. It expands the MIME-Version check to include the other headers mentioned.  If the values are different, an error is thrown.  There is support to allow 'known' values and not throw an error.

Should I create a pull request or can I get feedback on the changes in the branch before creating a pull request?  Still learning protocol.

thanks,
...chris.

**Comment by sunshineco** [comment]
Thanks for working on this. I left some comments on your changes to the code in e8613484f556c204c608e2463ba40ee1baab7143. The comments are mostly minor and may or may not even be actionable (depending upon whether or not I'm understanding the code correctly).

**Comment by dscho** [comment]
@webstech thank you for jumping on this!

> Should I create a pull request

Please do!

**Comment by webstech** [comment]
@sunshineco Thanks for the comments.  I have added responses.

In response I have refactored the code to make the positioning clearer (I hope) and added tests to help prove it is working.

Is it preferred that the code updates be in a new commit or just amend the prior one?  Waiting for the answer to this before pushing.  Also outstanding is the question of whether the DRY stuff (~line 770) should be removed/reverted.

thanks,
...chris.

**Comment by sunshineco** [comment]
> Is it preferred that the code updates be in a new commit or just amend the prior one? Waiting for the answer to this before pushing. 

Amending the existing commit makes it easier for people to review and understand the changes as a whole (rather than having to first understand one patch which itself has problems, followed by another patch which fixes those problems).

> Also outstanding is the question of whether the DRY stuff (~line 770) should be removed/reverted.

Judging from how the code looks in the original patch, even with the magic numbers replaced by an `enum`, I'd say the loss of readability probably isn't worth it. Considering that this code is not likely to change often, simple in-code comments saying to keep the table and code in-sync may be sufficient, without much negative impact on maintainability (despite not being DRY). So, I'd vote for dropping that change, though, of course, it's @dscho's call.

**Comment by sunshineco** [comment]
> I'd say the loss of readability probably isn't worth it.

Having said that, I can imagine a new function driven by the `IDupHeaders` table which produces the entire set of `--add-header=` flags. If, say, the function is named `addSingletonHeaders()`, then `generateMBox()` could construct its `args` like this:

```
const args = [
    "format-patch", "--thread", "--stdout", "--signature=gitgitgadget",
    "--add-header=Fcc: Sent"
    ].concat(addSingletonHeaders());
```

The functionality of `addSingleHeaders()` could be quite simple, just iterating over each element of `IDupHeaders` and generating an `--add-header=` flag from the key and the _first_ value for each item, skipping items which don't have a value. To keep it simple, you don't even need the `default` member.

**Comment by dscho** [comment]
> Is it preferred that the code updates be in a new commit or just amend the prior one?

I like the same flow as on the Git mailing list: amend and force-push. In contrast to the Git mailing list, I like the UI of GitHub PRs, where it is easy to see even "outdated" comments, i.e. conversations about commits that were "force-pushed away". If we keep discussing the commits *outside* of any PRs, those conversations will be lost.

**Comment by webstech** [comment]
Apologies for changing  branches.  I had pulled other changes from master and amend was not working on the commit I had wanted.  If there is other cleanup needed please let me know what to do.

**Comment by webstech** [comment]
Changed to remove most extra math and add addSingleHeaders.  Updated tests to add some extra white space tests.  Changed from throwing an error to just logging the difference to avoid breaking anything.  After looking at a few emails, there were a number of variations on Content-Type.

**Comment by sunshineco** [comment]
This is in your `RemDupMailHdrs` branch?

**Comment by webstech** [comment]
> This is in your `RemDupMailHdrs` branch?

Yes.  I stupidly merged the master update into the other branch.

**Comment by sunshineco** [comment]
Okay, I'll try to find some time to review it. Thanks.
