### ISSUE TITLE
Prevent stupidly large patch series, as well as PRs with merge commits

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/gitgitgadget#82]
It's probably safe to say that something like three dozen patches in one go are too much for any reviewer, even for the most exciting contributions.

So let's disallow it, also notifying the user of that fact when they push such a thing.

While at it, also holler about merge commits in the PR, as that cannot be reflected by `git format-patch`.

**Comment by webstech** [comment]
Should this be a github action for a PR/push update?  If not, why not?  Just looking for preferred direction.

**Comment by dscho** [comment]
I would _love_ for this to happen, but GitHub Actions need to be added to the target branch, and we do not control `master`.

I think it would be much easier to implement a simple check, such as generating the `git rev-list --parents ${baseCommit}..${tipCommit}`, then counting the number of lines (I think we should disallow patch series larger than 30 commits by default, probably with some way to exempt a given PR), and then verifying that there are no lines with two spaces in them (that would be a merge commit).

**Comment by webstech** [comment]
So webhooks would be added for pull_request and push events?  The azure-function/index.js would handle these and trigger a next step.  misc-helper.ts and ci-helper.ts would provide support for handling the events.  This would be the same for issue #120.  I am not clear on where misc-helper is identified to be run.  Is that in azure setup?  Let me know if this is the design you had in mind.

**Comment by dscho** [comment]
> So webhooks would be added for pull_request and push events?

That is already the case...

>  The azure-function/index.js would handle these and trigger a next step.

The `issue_comment` events are handled by the Azure Function, triggering the [Azure Pipeline](https://dev.azure.com/gitgitgadget/git/_build?definitionId=3).

But the `push` event (and also the `pull_request` event) is not handled by the Azure Function. It is handled via the Azure Pipeline being configured as "Pull request validation". That also allows it to be shown in the Checks part of the PR.

You can see the difference on https://dev.azure.com/gitgitgadget/git/_build?definitionId=3: the `push`-triggered builds are labeled as "Pull request build", and the `issue_comment` ones as "Manual build" (because they are triggered using a Personal Access Token ("PAT") that I created).

> misc-helper.ts and ci-helper.ts would provide support for handling the events.

Right. `misc-helper.ts` is called with `handle-pr-comment` or with `handle-pr-push`, respectively. (This already works.)

**Comment by webstech** [comment]
Thanks for the explanation (feeling a bit dumb at the moment for not recognizing handle-pr-push for what it is).  Now I understand where the "Manual build" comes from.

What do you think about using the GitHub api for the checks?  The reason being GitHub is providing json instead of having to parse git output.  The pull request has the commit count in it.  Very easy to add to the IPullRequestInfo. Should the "mergeable" value be returned as well?  The pull/nnn/commits output will have a parent length > 1 for a merge.

I am assuming the checks will be needed for both a push (to fail the validation) and a /submit comment (there is nothing in the PR to indicate  CI has failed).

Regarding an override, would this be through a special line in the PR description (eg commit-limit: 33)?  Will updating the PR cause the validation to run or will the user need to push the updates again (not exactly user friendly)?

**Comment by dscho** [comment]
> Thanks for the explanation (feeling a bit dumb at the moment for not recognizing handle-pr-push for what it is). Now I understand where the "Manual build" comes from.

Oh, please don't feel embarrassed. It is a bit of a complicated setup, and I am amazed that it works.

> What do you think about using the GitHub api for the checks?

My main reason for not using them is that they add roundtrips, i.e. make everything slower, and they also add another point of failure. I'd rather parse the output of Git, TBH. It's not difficult, anyway.

>  The pull request has the commit count in it. Very easy to add to the IPullRequestInfo.

Sure, but I'd like to look for merge commits, too, and I don't think there is a one-shot call to the GitHub API to request that.

> Should the "mergeable" value be returned as well?

Don't we do that already? I remember a recent `/submit` being rejected because the PR was not mergeable. I think it was the `git log --graph` one.

> The pull/nnn/commits output will have a parent length > 1 for a merge.

Oh, does that give us _all_ of the commits in the PR? With the commit messages? In that case, I would be in favor.

> I am assuming the checks will be needed for both a push (to fail the validation) and a /submit comment (there is nothing in the PR to indicate CI has failed).

That's a much neater idea than what I had in mind... I meant to give feedback via a comment upon `push`. I like your idea better.

> Regarding an override, would this be through a special line in the PR description (eg commit-limit: 33)? Will updating the PR cause the validation to run or will the user need to push the updates again (not exactly user friendly)?

I'd rather think about that when the need arises. I don't necessarily expect abuses, but maybe it is not the best idea to let _everybody_ override?

My gut feeling says that it might be good enough a UI to require a manual override via running a script locally that updates the `refs/notes/gitgitgadget`  to add an entry to the `IGitGitGadgetOptions` that are stored in that ref. That way, only people with `push` permission would be allowed to add such an override.

But maybe that is too paranoid?

**Comment by dscho** [comment]
> What do you think about using the GitHub api for the checks?

I just had another idea, and that one would _not_ work with the API alone: if you run `git log --oneline --check`, you will see whitespace problems. I think it would be nice to _at least_ warn about them. But you need the commits locally for that.

**Comment by webstech** [comment]
> I just had another idea, and that one would _not_ work with the API alone: if you run `git log --oneline --check`, you will see whitespace problems. I think it would be nice to _at least_ warn about them. But you need the commits locally for that.

At first I thought you meant whitespace problems in the commit messages.  😀  After testing that I can verify the github api does not remove any whitespace so linting commit messages for whitespace is possible.

Back to `--check` output, I don't disagree but is that another layer of checks - ie commit content linting?  This issue is for 'submit-able' level of PR linting.  Issue #120 is for commit message linting and issue #136 is for pull request comment linting.  Would this be better addressed with a QA test that had `git log --oneline --check -n 1` (with an appropriate value of '-n')?  Just trying to think about how to catch issues sooner - am I missing that there is no way to do `--check` before committing work?

**Comment by dscho** [comment]
> I don't disagree but is that another layer of checks - ie commit content linting?

@webstech it _is_ another layer. But if we plan on going in that direction anyway (and I do), then it might not make sense to introduce calls to the GitHub API to look for commits' information for one layer only to parse the local commits manually for another layer anyway.

In my mind, this should all be done in one go, although the implementation should of course happen incrementally.

>  Just trying to think about how to catch issues sooner - am I missing that there is no way to do `--check` before committing work?

Of course there is! But did you know about this feature? Neither do _most_ of GitGitGadget's users, especially the one-off contributors I'd like not to lose (and who are a big reason I started GitGitGadget in the first place, another reason being my own, personal convenience 😁).

**Comment by dscho** [comment]
This is now addressed, via #178 and #184 (I slipped that "no merge commits" commit into the latter).
