### ISSUE TITLE
Optionally skip sending a cover letter

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/gitgitgadget#85]
This is a bit tricky, even if the original shell script allowed for it.

My current idea is to detect an empty description (and/or have some magic first line like `/nocoverletter` or `/nocover` or `/skipcover`) and insert the relevant info after the `--` just like the original shell script did when no branch description was available for a single-patch "series".

Cc: @nasamuffin

**Comment by nasamuffin** [comment]
Can `/submit` take args? `/submit nocoverletter` maybe? I haven't looked at the implementation of gitgitgadget yet, so maybe that's not possible :)

**Comment by dscho** [comment]
Pretty much everything is possible ;-)

But in this instance, I'd rather have something that you cannot forget as easily (or for that matter, misspell as easily) as an option to `/submit`.

We could, however, introduce a new command `/nocoverletter`.

FWIW my idea to leave the cover letter empty does not really work, as it prevents you from adding a nice "Changes since v<previous>" section.

But we could have a magic thing in the cover letter, like starting it with `/nocoverletter` on its own line. The welcome message also could talk about this, to make it more obvious how to use this.

**Comment by nasamuffin** [comment]
Okay, so in that case, what if your feedback leads to you adding a second commit, and wanting to add a cover letter now that you have two patches?

Or are you thinking the PR description should begin with `/nocoverletter` to indicate it should be included after `---` in the single email (and then modified to remove `/nocoverletter` when someone adds a second commit and changes the PR description)?

**Comment by dscho** [comment]
> Or are you thinking the PR description should begin with `/nocoverletter` to indicate it should be included after `---` in the single email (and then modified to remove `/nocoverletter` when someone adds a second commit and changes the PR description)?

That was what I was thinking about, with GitGitGadget erroring out when it finds a `/nocoverletter` in a multi-patch PR.

**Comment by dscho** [comment]
OTOH I also offered this idea [on IRC](https://colabti.org/irclogger/irclogger_log/git-devel?date=2019-10-25#l15):

> My  original Unix shell script, which I transmogrified into what became  GitGitGadget, was able to suppress the cover letter based on the absence  of a `branch.<name>.description`, and it should not be _too_ hard  to teach GitGitGadget the same trick: empty PR description -> put  the range-diff between the commit message and the actual patch, indented by a space.
>
> Of  course, you still might want to summarize the changes (see e.g. how I  edited this PR description between iterations to add the "Changes since  v1" part: https://github.com/gitgitgadget/git/pull/410#issue-330127116),  in which case it would get a bit tricky, unless you say: well, we won't  send cover letters with single-patch mails, ever, and always fold the PR description in, between the commit message and the diff.

I guess that the idea to fold in the PR description into single-patch "series" rather than sending a cover letter would be _very_ much welcomed on the Git mailing list.

**Comment by sunshineco** [comment]
> put the range-diff between the commit message and the actual patch, indented by a space.

As a point of interest, when I implemented the `--range-diff` option of `git format-patch`, I considered indenting the _range-diff_ when inserting it into a stand-alone patch (no cover letter) but then realized that neither `git am` nor `git apply` would be confused by it even when not indented, so `git format-patch --range-diff` does no indentation. (On the other hand, with `git format-patch --interdiff`, I did implement indenting since an _interdiff_ would confuse `git am` in a stand-alone patch.)

**Comment by dscho** [comment]
@sunshineco you're right! It is totally unnecessary to indent the range-diff. In my original shell script, I included interdiffs (and my, were they hard to generate when I had to rebase between iterations!) and that obviously had to be indented, hence my confusion.

**Comment by dscho** [comment]
And I think I'd like to modify my proposal yet again: there seems to be a very, very, _very_ strong preference by the Git maintainer to have _no_ cover letter at all for single-patch contributions. So let's do this. Let's always fold the PR description (modulo template text, that is) between the commit message and the diffstat if there is only a single commit to submit.

**Comment by dscho** [comment]
> It is totally unnecessary to indent the range-diff.

Note that the PR description _still_ needs to be indented because it could contain a line starting with `From:` (which is not legal in email bodies).

**Comment by sunshineco** [comment]
> Note that the PR description still needs to be indented because it could contain a line starting with From: (which is not legal in email bodies).

Indeed, and in that sense, the PR description is much like notes inserted with `git format-patch --notes` which do get indented.

And it's not only `From` in the PR description which can be problematic. Other text could confuse `git-am`; for instance a `---` line or even a raw diff if someone happens to paste it into the PR description. So, indenting the PR description is definitely warranted.

**Comment by dscho** [comment]
> the PR description is much like notes inserted with `git format-patch --notes` which do get indented.

@sunshineco off the top of your head, do you remember by how many columns?

**Comment by sunshineco** [comment]
> off the top of your head, do you remember by how many columns?

Notes are indented 4 spaces.

(The literal "Notes:" title, on the other hand, is not indented.)

**Comment by dscho** [comment]
Thank you! I thought I remembered that, and started to implement it that way.
