### ISSUE TITLE
Be more lenient with white-space in PR comments

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/gitgitgadget#94]
When issuing an `/allow hello ` (with a trailing space), GitGitGadget is a bit dense, and adds "hello " (with a trailing space) to the list of allowed users.

We might even want to go one step further and make sure that that user exists.

Another step further might be to handle `/allow` without arguments to mean the author of the current PR.

Yet another step would add code to maintain an internal map from GitHub handles to clear names and email addresses, so that PR authors are auto-Cc:ed on their submitted patches.

**Comment by webstech** [comment]
Pull request #101 was opened to address the first three parts of this.

The last step should probably be a separate issue.  Github may not have a public email address for the PR author.  GitHubGlue could provide an interface to what is known:
export interface IGHUser {
    email: string;                  // null if no public email
    login: string;
    name: string;
    type: string;
}

**Comment by webstech** [comment]
@dscho Can this be closed now?

**Comment by dscho** [comment]
> Can this be closed now?

Yes! Thanks!
